window.esdocSearchIndex = [
  [
    "timer_app/src/components/editabletimer.js~editabletimer",
    "class/src/components/EditableTimer.js~EditableTimer.html",
    "<span>EditableTimer</span> <span class=\"search-result-import-path\">timer_app/src/components/EditableTimer.js</span>",
    "class"
  ],
  [
    "timer_app/src/components/editabletimerlist.js~editabletimerlist",
    "class/src/components/EditableTimerList.js~EditableTimerList.html",
    "<span>EditableTimerList</span> <span class=\"search-result-import-path\">timer_app/src/components/EditableTimerList.js</span>",
    "class"
  ],
  [
    "timer_app/src/helpers/servercommunication.js~servercommunication",
    "class/src/helpers/serverCommunication.js~ServerCommunication.html",
    "<span>ServerCommunication</span> <span class=\"search-result-import-path\">timer_app/src/helpers/serverCommunication.js</span>",
    "class"
  ],
  [
    "timer_app/src/components/timer.js~timer",
    "class/src/components/Timer.js~Timer.html",
    "<span>Timer</span> <span class=\"search-result-import-path\">timer_app/src/components/Timer.js</span>",
    "class"
  ],
  [
    "timer_app/src/components/timeractionbutton.js~timeractionbutton",
    "class/src/components/TimerActionButton.js~TimerActionButton.html",
    "<span>TimerActionButton</span> <span class=\"search-result-import-path\">timer_app/src/components/TimerActionButton.js</span>",
    "class"
  ],
  [
    "timer_app/src/components/timerform.js~timerform",
    "class/src/components/TimerForm.js~TimerForm.html",
    "<span>TimerForm</span> <span class=\"search-result-import-path\">timer_app/src/components/TimerForm.js</span>",
    "class"
  ],
  [
    "timer_app/src/components/timersdashboard.js~timersdashboard",
    "class/src/components/TimersDashboard.js~TimersDashboard.html",
    "<span>TimersDashboard</span> <span class=\"search-result-import-path\">timer_app/src/components/TimersDashboard.js</span>",
    "class"
  ],
  [
    "timer_app/src/components/toggleabletimerform.js~toggleabletimerform",
    "class/src/components/ToggleableTimerForm.js~ToggleableTimerForm.html",
    "<span>ToggleableTimerForm</span> <span class=\"search-result-import-path\">timer_app/src/components/ToggleableTimerForm.js</span>",
    "class"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~arraybuffer",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ArrayBuffer",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~dataview",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~DataView",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~date",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Date",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~error",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Error",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~evalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~EvalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float64array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float64Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generator",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Generator",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generatorfunction",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~GeneratorFunction",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~infinity",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Infinity",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~internalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~InternalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~json",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~JSON",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~map",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Map",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~nan",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~NaN",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~promise",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Promise",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~proxy",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Proxy",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~rangeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RangeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~referenceerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ReferenceError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~reflect",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Reflect",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~regexp",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RegExp",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~set",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Set",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~String",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~symbol",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Symbol",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~syntaxerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~SyntaxError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~typeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~TypeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~urierror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~URIError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8clampedarray",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8ClampedArray",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakmap",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakMap",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakset",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakSet",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~null",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~null",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~string",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~undefined",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~undefined",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~audiocontext",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~AudioContext",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~canvasrenderingcontext2d",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~CanvasRenderingContext2D",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~documentfragment",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~DocumentFragment",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~element",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Element",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~event",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Event",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~node",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Node",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~nodelist",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~NodeList",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~xmlhttprequest",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~XMLHttpRequest",
    "external"
  ],
  [
    "src/app.js",
    "file/src/app.js.html",
    "src/app.js",
    "file"
  ],
  [
    "src/client.js",
    "file/src/client.js.html",
    "src/client.js",
    "file"
  ],
  [
    "src/components/editabletimer.js",
    "file/src/components/EditableTimer.js.html",
    "src/components/EditableTimer.js",
    "file"
  ],
  [
    "src/components/editabletimer.js~editabletimer#render",
    "class/src/components/EditableTimer.js~EditableTimer.html#instance-method-render",
    "src/components/EditableTimer.js~EditableTimer#render",
    "method"
  ],
  [
    "src/components/editabletimerlist.js",
    "file/src/components/EditableTimerList.js.html",
    "src/components/EditableTimerList.js",
    "file"
  ],
  [
    "src/components/editabletimerlist.js~editabletimerlist#render",
    "class/src/components/EditableTimerList.js~EditableTimerList.html#instance-method-render",
    "src/components/EditableTimerList.js~EditableTimerList#render",
    "method"
  ],
  [
    "src/components/timer.js",
    "file/src/components/Timer.js.html",
    "src/components/Timer.js",
    "file"
  ],
  [
    "src/components/timer.js~timer#componentdidmount",
    "class/src/components/Timer.js~Timer.html#instance-method-componentDidMount",
    "src/components/Timer.js~Timer#componentDidMount",
    "method"
  ],
  [
    "src/components/timer.js~timer#componentwillunmount",
    "class/src/components/Timer.js~Timer.html#instance-method-componentWillUnmount",
    "src/components/Timer.js~Timer#componentWillUnmount",
    "method"
  ],
  [
    "src/components/timer.js~timer#forceupdateinterval",
    "class/src/components/Timer.js~Timer.html#instance-member-forceUpdateInterval",
    "src/components/Timer.js~Timer#forceUpdateInterval",
    "member"
  ],
  [
    "src/components/timer.js~timer#render",
    "class/src/components/Timer.js~Timer.html#instance-method-render",
    "src/components/Timer.js~Timer#render",
    "method"
  ],
  [
    "src/components/timeractionbutton.js",
    "file/src/components/TimerActionButton.js.html",
    "src/components/TimerActionButton.js",
    "file"
  ],
  [
    "src/components/timeractionbutton.js~timeractionbutton#render",
    "class/src/components/TimerActionButton.js~TimerActionButton.html#instance-method-render",
    "src/components/TimerActionButton.js~TimerActionButton#render",
    "method"
  ],
  [
    "src/components/timerform.js",
    "file/src/components/TimerForm.js.html",
    "src/components/TimerForm.js",
    "file"
  ],
  [
    "src/components/timerform.js~timerform#render",
    "class/src/components/TimerForm.js~TimerForm.html#instance-method-render",
    "src/components/TimerForm.js~TimerForm#render",
    "method"
  ],
  [
    "src/components/timersdashboard.js",
    "file/src/components/TimersDashboard.js.html",
    "src/components/TimersDashboard.js",
    "file"
  ],
  [
    "src/components/timersdashboard.js~timersdashboard#ajaxinterval",
    "class/src/components/TimersDashboard.js~TimersDashboard.html#instance-member-ajaxInterval",
    "src/components/TimersDashboard.js~TimersDashboard#ajaxInterval",
    "member"
  ],
  [
    "src/components/timersdashboard.js~timersdashboard#componentdidmount",
    "class/src/components/TimersDashboard.js~TimersDashboard.html#instance-method-componentDidMount",
    "src/components/TimersDashboard.js~TimersDashboard#componentDidMount",
    "method"
  ],
  [
    "src/components/timersdashboard.js~timersdashboard#componentwillunmount",
    "class/src/components/TimersDashboard.js~TimersDashboard.html#instance-method-componentWillUnmount",
    "src/components/TimersDashboard.js~TimersDashboard#componentWillUnmount",
    "method"
  ],
  [
    "src/components/timersdashboard.js~timersdashboard#createtimer",
    "class/src/components/TimersDashboard.js~TimersDashboard.html#instance-method-createTimer",
    "src/components/TimersDashboard.js~TimersDashboard#createTimer",
    "method"
  ],
  [
    "src/components/timersdashboard.js~timersdashboard#deletetimer",
    "class/src/components/TimersDashboard.js~TimersDashboard.html#instance-method-deleteTimer",
    "src/components/TimersDashboard.js~TimersDashboard#deleteTimer",
    "method"
  ],
  [
    "src/components/timersdashboard.js~timersdashboard#render",
    "class/src/components/TimersDashboard.js~TimersDashboard.html#instance-method-render",
    "src/components/TimersDashboard.js~TimersDashboard#render",
    "method"
  ],
  [
    "src/components/timersdashboard.js~timersdashboard#starttimer",
    "class/src/components/TimersDashboard.js~TimersDashboard.html#instance-method-startTimer",
    "src/components/TimersDashboard.js~TimersDashboard#startTimer",
    "method"
  ],
  [
    "src/components/timersdashboard.js~timersdashboard#stoptimer",
    "class/src/components/TimersDashboard.js~TimersDashboard.html#instance-method-stopTimer",
    "src/components/TimersDashboard.js~TimersDashboard#stopTimer",
    "method"
  ],
  [
    "src/components/timersdashboard.js~timersdashboard#updatetimer",
    "class/src/components/TimersDashboard.js~TimersDashboard.html#instance-method-updateTimer",
    "src/components/TimersDashboard.js~TimersDashboard#updateTimer",
    "method"
  ],
  [
    "src/components/timersdashboard.js~timersdashboard#updatetimerbyid",
    "class/src/components/TimersDashboard.js~TimersDashboard.html#instance-method-updateTimerById",
    "src/components/TimersDashboard.js~TimersDashboard#updateTimerById",
    "method"
  ],
  [
    "src/components/timersdashboard.js~timersdashboard.byid",
    "class/src/components/TimersDashboard.js~TimersDashboard.html#static-method-byId",
    "src/components/TimersDashboard.js~TimersDashboard.byId",
    "method"
  ],
  [
    "src/components/toggleabletimerform.js",
    "file/src/components/ToggleableTimerForm.js.html",
    "src/components/ToggleableTimerForm.js",
    "file"
  ],
  [
    "src/components/toggleabletimerform.js~toggleabletimerform#render",
    "class/src/components/ToggleableTimerForm.js~ToggleableTimerForm.html#instance-method-render",
    "src/components/ToggleableTimerForm.js~ToggleableTimerForm#render",
    "method"
  ],
  [
    "src/helpers.js",
    "file/src/helpers.js.html",
    "src/helpers.js",
    "file"
  ],
  [
    "src/helpers/servercommunication.js",
    "file/src/helpers/serverCommunication.js.html",
    "src/helpers/serverCommunication.js",
    "file"
  ],
  [
    "src/helpers/servercommunication.js~servercommunication#baseurl",
    "class/src/helpers/serverCommunication.js~ServerCommunication.html#instance-member-baseUrl",
    "src/helpers/serverCommunication.js~ServerCommunication#baseUrl",
    "member"
  ],
  [
    "src/helpers/servercommunication.js~servercommunication#constructor",
    "class/src/helpers/serverCommunication.js~ServerCommunication.html#instance-constructor-constructor",
    "src/helpers/serverCommunication.js~ServerCommunication#constructor",
    "method"
  ],
  [
    "src/helpers/servercommunication.js~servercommunication#createtimer",
    "class/src/helpers/serverCommunication.js~ServerCommunication.html#instance-method-createTimer",
    "src/helpers/serverCommunication.js~ServerCommunication#createTimer",
    "method"
  ],
  [
    "src/helpers/servercommunication.js~servercommunication#deletetimer",
    "class/src/helpers/serverCommunication.js~ServerCommunication.html#instance-method-deleteTimer",
    "src/helpers/serverCommunication.js~ServerCommunication#deleteTimer",
    "method"
  ],
  [
    "src/helpers/servercommunication.js~servercommunication#gettimers",
    "class/src/helpers/serverCommunication.js~ServerCommunication.html#instance-method-getTimers",
    "src/helpers/serverCommunication.js~ServerCommunication#getTimers",
    "method"
  ],
  [
    "src/helpers/servercommunication.js~servercommunication#starttimer",
    "class/src/helpers/serverCommunication.js~ServerCommunication.html#instance-method-startTimer",
    "src/helpers/serverCommunication.js~ServerCommunication#startTimer",
    "method"
  ],
  [
    "src/helpers/servercommunication.js~servercommunication#stoptimer",
    "class/src/helpers/serverCommunication.js~ServerCommunication.html#instance-method-stopTimer",
    "src/helpers/serverCommunication.js~ServerCommunication#stopTimer",
    "method"
  ],
  [
    "src/helpers/servercommunication.js~servercommunication#updatetimer",
    "class/src/helpers/serverCommunication.js~ServerCommunication.html#instance-method-updateTimer",
    "src/helpers/serverCommunication.js~ServerCommunication#updateTimer",
    "method"
  ],
  [
    "src/helpers/servercommunication.js~servercommunication.apitimer",
    "typedef/index.html#static-typedef-APITimer",
    "src/helpers/serverCommunication.js~ServerCommunication.APITimer",
    "typedef"
  ]
]